# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-20 01:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorInfo',
            fields=[
                ('url_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True, verbose_name='email')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Contact number format(10 digits): ex: 8050248326', regex='^[1-9]{1}[0-9]{9}$')])),
                ('dob', models.DateField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('professional_status', models.CharField(choices=[(10, 'Student'), (20, 'Looking For Job'), (30, 'Employed')], default=10, max_length=100)),
                ('technical_skills', models.CharField(max_length=500)),
                ('other_skills', models.CharField(max_length=500)),
                ('technology_of_interest', models.CharField(max_length=500)),
                ('work_experience', models.CharField(max_length=500)),
                ('project_undertaken', models.CharField(max_length=500)),
                ('publications', models.CharField(max_length=500)),
                ('achievements', models.CharField(max_length=500)),
                ('hobbies', models.CharField(max_length=500)),
                ('heard', models.CharField(max_length=500, verbose_name='Where Did You Hear About Ambassador Program')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(10, 'Applied'), (20, 'On Hold'), (30, 'Selected')], default=10, max_length=100)),
            ],
        ),
    ]
