# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-20 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorinfo',
            name='professional_status',
            field=models.CharField(choices=[('student', 'Student'), ('looking', 'Looking For Job'), ('employed', 'Employed')], default=10, max_length=100),
        ),
        migrations.AlterField(
            model_name='ambassadorinfo',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('on_hold', 'On Hold'), ('selected', 'Selected')], default=10, max_length=100),
        ),
    ]
