# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-20 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190120_0245'),
        ('kratos', '0002_auto_20190120_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amb_user', to='profiles.Profile'),
        ),
    ]
