# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-20 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kratos', '0004_auto_20190120_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorinfo',
            name='other_skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ambassadorinfo',
            name='project_undertaken',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ambassadorinfo',
            name='publications',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ambassadorinfo',
            name='work_experience',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
