# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firebase_chat_id',
            field=models.TextField(default=None, null=True, verbose_name='Firebase chat id'),
        ),
    ]
