# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-20 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_firebase_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=100, verbose_name='event_id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_sent', to='profiles.Profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_received', to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'Event Connection',
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventconnection',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
